// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvfwmlbsxcdvowgudyjk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2ZndtbGJzeGNkdm93Z3VkeWprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNTUyMTUsImV4cCI6MjA3MTYzMTIxNX0.mfM1ZdJi0aGPH4zXR1LClUmuPEQgByp5i6xgQcPY5B0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});